[package]
name = "lagrange-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"] # For WebAssembly

[dependencies]
wasm-bindgen = "0.2" # Allows Rust to interact with JavaScript
